spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tabula?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id: 123
#            client-secret: 123
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  logging:
    level:
      liquibase:DEBUG

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
