services:
  db:
    image: mysql:8.0.42
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sa_rest
      - MYSQL_ROOT_PASSWORD=root123

  sample:
    depends_on:
      - db
    image: georgib/docker-sample:v1
    ports:
      - "80:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123

volumes:
  db: {}
